import { VOCABULARY_VERSION, type ProductVocabulary } from "./product-vocabulary";
import { CATALOG_PRODUCT_CONCEPTS } from "./product-vocabulary-catalog-data";
import { V007_DATASET_PRODUCT_CONCEPTS } from "./v007-dataset-product-vocabulary";

/**
 * Initial conservative product vocabulary for `product-vocabulary.v1`.
 *
 * Evidence sources (read-only, no dataset regenerated by this file):
 * - data/processed/lora-v004-composicion.json (`shopify.elementos`): real
 *   catalog SKU + title + variant rows observed across the v004 dataset.
 * - docs/decisions/product-vocabulary-v001.md: frozen scope, Reflex-stays-Reflex
 *   rule, gold/rose gold must stay distinct.
 * - writing-block.md §§3,7,8: schema shape, canonical label style, resolver
 *   precedence, and required invariants.
 *
 * Scope: only concepts with multiple corroborating SKU rows (or a single row
 * that is unambiguous and structurally distinct, e.g. the rose-gold pair that
 * must never collapse into gold) are marked "active". Anything not directly
 * evidenced by the sources above (assorted/mixed colors, individual foil
 * digits, additional finishes only seen once) is left out entirely rather
 * than guessed.
 */
export const PRODUCT_VOCABULARY: ProductVocabulary = [
  {
    concept_id: "balloon.round.latex.reflex.gold",
    canonical_label: "round latex balloon in gold with a Reflex high-shine finish",
    catalog_titles: ["GLOBO LATEX REDONDO REFLEX DORADO", "GLOBO REDONDO REFLEX DORADO"],
    visual: {
      family: "Reflex",
      shape: "round",
      material: "latex",
      color: "gold",
      finish: "Reflex high-shine",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo reflex dorado", "globo redondo reflex dorado", "globo reflex dorado", "reflex dorado"],
      en: ["round reflex gold balloon", "gold reflex balloon", "gold reflex", "chrome gold balloon"],
      contextual: [{ value: "dorado", required_tokens: ["reflex"] }],
    },
    catalog_product_ids: ["20014242", "20017754", "20014155", "20014156", "20015523", "20014169", "20014725", "7109611258049"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.reflex.rose_gold",
    canonical_label: "round latex balloon in rose gold with a Reflex high-shine finish",
    catalog_titles: ["GLOBO REDONDO REFLEX DORADO ROSA", "GLOBO LATEX REDONDO REFLEX DORADO ROSA"],
    visual: {
      family: "Reflex",
      shape: "round",
      material: "latex",
      color: "rose gold",
      finish: "Reflex high-shine",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo reflex dorado rosa", "globo redondo reflex dorado rosa", "globo reflex dorado rosa", "dorado rosa reflex", "reflex dorado rosa", "reflex rosa dorado"],
      en: ["rose gold reflex balloon", "rose gold reflex", "reflex rose gold balloon", "round reflex rose gold balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20014157", "7109611323585"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-12", "R-18", "R-24"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.reflex.silver",
    canonical_label: "round latex balloon in silver with a Reflex high-shine finish",
    catalog_titles: ["GLOBO LATEX REDONDO REFLEX PLATA"],
    visual: {
      family: "Reflex",
      shape: "round",
      material: "latex",
      color: "silver",
      finish: "Reflex high-shine",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo reflex plata", "globo redondo reflex plata", "globo reflex plata", "reflex plata"],
      en: ["round reflex silver balloon", "silver reflex balloon", "silver reflex", "chrome silver balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20014244", "20014171", "20014724", "20014160", "20017756", "20014159", "20015517", "7109611520193"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18", "R-24"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.reflex.blue",
    canonical_label: "round latex balloon in blue with a Reflex high-shine finish",
    visual: {
      family: "Reflex",
      shape: "round",
      material: "latex",
      color: "blue",
      finish: "Reflex high-shine",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo reflex azul", "globo redondo reflex azul"],
      en: ["round reflex blue balloon", "blue reflex balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20014240", "20014151", "20014152"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.reflex.pink",
    canonical_label: "round latex balloon in pink with a Reflex high-shine finish",
    catalog_titles: ["GLOBO REDONDO REFLEX ROSADO"],
    visual: {
      family: "Reflex",
      shape: "round",
      material: "latex",
      color: "pink",
      finish: "Reflex high-shine",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo reflex rosado", "globo redondo reflex rosado", "globo reflex rosado", "reflex rosado"],
      en: ["round reflex pink balloon", "pink reflex balloon", "pink reflex"],
      contextual: [],
    },
    catalog_product_ids: ["7109611618497"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.satin.pink",
    canonical_label: "round latex balloon in pink with a Satin sheen finish",
    catalog_titles: ["GLOBO REDONDO SATIN ROSADO"],
    visual: {
      family: "Satin",
      shape: "round",
      material: "latex",
      color: "pink",
      finish: "Satin sheen",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo satin rosado", "globo redondo satin rosado", "globo satin rosado", "satin rosado"],
      en: ["round satin pink balloon", "pink satin balloon", "pink satin"],
      contextual: [],
    },
    catalog_product_ids: ["7109612732609"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.reflex.violet",
    canonical_label: "round latex balloon in violet with a Reflex high-shine finish",
    visual: {
      family: "Reflex",
      shape: "round",
      material: "latex",
      color: "violet",
      finish: "Reflex high-shine",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo redondo reflex violeta", "globo latex redondo reflex violeta"],
      en: ["round reflex violet balloon", "violet reflex balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20014246", "20014163"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.pink",
    canonical_label: "round latex balloon in pink, solid Fashion finish",
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "pink",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    // "Rosa" y "Rosado" son el mismo color re-listado tras un renombre del catálogo, no dos
    // rosas distintos: el catálogo trae los dos títulos en paralelo para cada forma (redondo,
    // tubito, Link-O-Loon), ambos con `colores: ["rosado"]` y la misma escalera de tamaños, y
    // los ids del par viejo empiezan en 71095… contra 10719… del nuevo. Confirmado y
    // fusionado acá para que no queden dos conceptos compitiendo por el mismo alias.
    aliases: {
      es: [
        "globo latex redondo fashion rosado",
        "globo redondo fashion rosado",
        "globo latex redondo fashion rosa",
        "globo redondo fashion rosa",
      ],
      en: ["round fashion pink balloon", "pink fashion balloon"],
      contextual: [],
    },
    catalog_titles: ["GLOBO LATEX REDONDO FASHION ROSADO", "GLOBO REDONDO FASHION ROSADO", "Globo Redondo Fashion Rosa"],
    catalog_product_ids: [
      "20000438", "20000578", "20000440", "20000725", "20000726", "20000577", "20000439", "20000576", "20000904", "20009574", "20012054",
      // Variantes del título "Rosa" (producto 10719259132097), fusionadas.
      "20019697", "20019698", "20019700", "20019701", "20019702", "20019704", "20019705", "20019708", "20019711", "20019845", "10719259132097",
    ],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18", "R-24", "R-36"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.sand",
    canonical_label: "round latex balloon in sand, solid Fashion finish",
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "sand",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo fashion arena", "globo redondo fashion arena"],
      en: ["round fashion sand balloon", "sand fashion balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20014535", "20014530", "20014532", "20014531", "20014529", "20016058", "20014536", "20014537"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18", "R-24"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.red",
    canonical_label: "round latex balloon in red, solid Fashion finish",
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "red",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo fashion rojo", "globo redondo fashion rojo"],
      en: ["round fashion red balloon", "red fashion balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20000444", "20000731", "20000730", "20000732", "20000582", "20000446"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.white",
    canonical_label: "round latex balloon in white, solid Fashion finish",
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "white",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo fashion blanco", "globo redondo fashion blanco"],
      en: ["round fashion white balloon", "white fashion balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20000435", "20000722", "20000575", "20000437", "20000436", "20000723", "20000721", "20000902", "20009573", "20000574"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18", "R-36"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.navy_blue",
    canonical_label: "round latex balloon in navy blue, solid Fashion finish",
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "navy blue",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo fashion azul naval", "globo redondo fashion azul naval"],
      en: ["round fashion navy blue balloon", "navy blue fashion balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20011609", "20013752", "20010801", "20010802", "20010804", "20010806"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.dusty_rose",
    canonical_label: "round latex balloon in dusty rose, solid Fashion finish",
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "dusty rose",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo fashion palo de rosa", "globo redondo fashion palo de rosa"],
      en: ["round fashion dusty rose balloon", "dusty rose fashion balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20010671", "20010675", "20010670", "20010673", "20016066"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  // These six live catalog-backed Fashion colours unblock product-linked scenes
  // from LORA_PRODUCT_VOCABULARY_FAILED.
  //
  // CORRECTED 2026-09-17. This comment used to claim the catalog "deliberately
  // has no single-colour round latex product for lila, turquesa, champagne,
  // coral, menta, nude, or burdeos". Queried against the live catalog, all
  // seven exist and are published:
  //   lila       8634232996135  Fashion Lila            R-5..R-36
  //   turquesa   8923545141543  Fashion Azul Turquesa   R-5..R-24
  //   champagne  8634269401383  Reflex Champaña         R-5..R-24
  //   coral      8634310426919  Fashion Coral Tropical  R-5..R-24
  //   menta      9407246172455  Silk Verde Menta        R-5..R-24
  //   nude       9885210738983  Pastel Mate Nude        R-5..R-24
  //   burdeos    8634257539367  Metal Vinotinto         R-5, R-9, R-12
  // champagne, coral, menta and nude are in fact already drawable through other
  // concepts, so for them the claim was merely stale. `burdeos` was the one that
  // cost a customer-visible failure and now has its own concept below.
  //
  // lila and turquesa stay undrawable for a different reason that adding a
  // concept would NOT fix: `clasificarColores` maps neither "lilac"/"lavender"
  // nor "turquoise" to a catalog colour, so a concept declaring them would
  // never reach a scene. Same for grey/gray → `gris`. Those are colour-taxonomy
  // aliases, and a taxonomy change is a person's decision, not a loop's.
  {
    concept_id: "balloon.round.latex.fashion.black",
    canonical_label: "round latex balloon in black, solid Fashion finish",
    catalog_titles: ["B2b Globo Latex Redondo Fashion Negro"],
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "black",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo fashion negro", "globo redondo fashion negro"],
      en: ["round fashion black balloon", "black fashion balloon"],
      contextual: [],
    },
    catalog_product_ids: ["8634239516967"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18", "R-24", "R-36", "R-40"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.purple",
    canonical_label: "round latex balloon in purple, solid Fashion finish",
    catalog_titles: ["B2b Globo Latex Redondo Fashion Orquidea Morada"],
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "purple",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo fashion orquidea morada", "globo redondo fashion orquidea morada"],
      en: ["round fashion purple balloon", "purple fashion balloon"],
      contextual: [],
    },
    catalog_product_ids: ["8634302464295"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-12", "R-18", "R-24"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.orange",
    canonical_label: "round latex balloon in orange, solid Fashion finish",
    catalog_titles: [
      "B2b Globo Latex Redondo Fashion Naranja",
      "B2b Globo Latex Redondo Fashion Naranja Cobrizo",
    ],
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "orange",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: [
        "globo latex redondo fashion naranja",
        "globo redondo fashion naranja",
        "globo latex redondo fashion naranja cobrizo",
        "globo redondo fashion naranja cobrizo",
      ],
      en: [
        "round fashion orange balloon",
        "orange fashion balloon",
        "round fashion copper orange balloon",
        "copper orange fashion balloon",
      ],
      contextual: [],
    },
    catalog_product_ids: ["8634238599463", "8901833097511"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18", "R-24", "R-40"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.yellow",
    canonical_label: "round latex balloon in yellow, solid Fashion finish",
    catalog_titles: [
      "B2b Globo Latex Redondo Fashion Amarillo",
      "B2b Globo Latex Redondo Fashion Amarillo Miel",
      "B2b Globo Latex Redondo Fashion Mostaza",
    ],
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "yellow",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: [
        "globo latex redondo fashion amarillo",
        "globo redondo fashion amarillo",
        "globo latex redondo fashion amarillo miel",
        "globo redondo fashion amarillo miel",
        "globo latex redondo fashion mostaza",
        "globo redondo fashion mostaza",
      ],
      en: [
        "round fashion yellow balloon",
        "yellow fashion balloon",
        "round fashion honey yellow balloon",
        "honey yellow fashion balloon",
        "round fashion mustard balloon",
        "mustard fashion balloon",
      ],
      contextual: [],
    },
    catalog_product_ids: ["8634239287591", "8634225295655", "8634229948711"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18", "R-24", "R-36", "R-40"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.brown",
    canonical_label: "round latex balloon in brown, solid Fashion finish",
    catalog_titles: [
      "B2b Globo Latex Redondo Fashion Café",
      "B2b Globo Latex Redondo Fashion Chocolate",
      "B2b Globo Latex Redondo Fashion Moca",
    ],
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "brown",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: [
        "globo latex redondo fashion cafe",
        "globo redondo fashion cafe",
        "globo latex redondo fashion chocolate",
        "globo redondo fashion chocolate",
        "globo latex redondo fashion moca",
        "globo redondo fashion moca",
      ],
      en: [
        "round fashion brown balloon",
        "brown fashion balloon",
        "round fashion chocolate brown balloon",
        "chocolate brown fashion balloon",
        "round fashion mocha balloon",
        "mocha fashion balloon",
      ],
      contextual: [],
    },
    catalog_product_ids: ["8634228834599", "8634238828839", "9874866831655"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18", "R-24"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.fashion.cream",
    canonical_label: "round latex balloon in cream, solid Fashion finish",
    catalog_titles: ["B2b Globo Latex Redondo Fashion Blush Crema"],
    visual: {
      family: "Fashion",
      shape: "round",
      material: "latex",
      color: "cream",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo fashion blush crema", "globo redondo fashion blush crema"],
      en: ["round fashion cream balloon", "cream fashion balloon"],
      contextual: [],
    },
    catalog_product_ids: ["10139567980839"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18", "R-24"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.satin.pearl",
    canonical_label: "round latex balloon in pearl with a Satin sheen finish",
    visual: {
      family: "Satin",
      shape: "round",
      material: "latex",
      color: "pearl",
      finish: "Satin sheen",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex redondo satin perla", "globo redondo satin perla"],
      en: ["round satin pearl balloon", "pearl satin balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20000518", "20000824", "20000661", "20000826"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.silk.gold",
    canonical_label: "round latex balloon in gold with a Silk sheen finish",
    visual: {
      family: "Silk",
      shape: "round",
      material: "latex",
      color: "gold",
      finish: "Silk sheen",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo redondo silk dorado", "globo latex redondo silk dorado"],
      en: ["round silk gold balloon", "gold silk balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20019317"],
    sizes: { separate: true, allowed_codes: ["R-5"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.pastel_matte.pink",
    canonical_label: "round latex balloon in pastel matte pink",
    visual: {
      family: "Pastel Matte",
      shape: "round",
      material: "latex",
      color: "pastel pink",
      finish: "pastel matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo redondo pastel mate rosado", "globo latex redondo pastel mate rosado"],
      en: ["round pastel matte pink balloon", "pastel matte pink balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20012264", "20012385"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.pastel_dusk.laurel_green",
    canonical_label: "round latex balloon in dusk laurel green",
    visual: {
      family: "Pastel Dusk",
      shape: "round",
      material: "latex",
      color: "laurel green",
      finish: "pastel dusk",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo redondo pastel dusk verde laurel", "globo latex redondo pastel dusk verde laurel"],
      en: ["round pastel dusk laurel green balloon", "dusk laurel green balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20017285", "20017145", "20017142", "20017286", "20017287", "20017149"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12", "R-18"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.metal.gold",
    canonical_label: "round latex balloon in gold with a metallic sheen finish",
    visual: {
      family: "Metal",
      shape: "round",
      material: "latex",
      color: "gold",
      finish: "metallic sheen",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo redondo metal dorado", "globo latex redondo metal dorado"],
      en: ["round metallic gold balloon", "metal gold balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20000562", "20000714", "20000883"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    // `burdeos` no tenía NINGÚN concepto, así que una referencia de vino y plata
    // no podía dibujarse en vino: la escena caía a dorado rosa y salía rosada.
    // El producto existe y está publicado — `B2b Globo Latex Redondo Metal
    // Vinotinto`, product_id 8634257539367, verificado contra el catálogo vivo
    // el 2026-09-17 — de modo que la exclusión se apoyaba en una afirmación
    // falsa (ver el comentario corregido más arriba).
    //
    // Los tres códigos son las variantes que existen; hoy solo R-9 está
    // disponible. La disponibilidad no se congela aquí a propósito: cambia a
    // diario y el snapshot de catálogo es la autoridad al cotizar.
    concept_id: "balloon.round.latex.metal.burgundy",
    canonical_label: "round latex balloon in burgundy with a metallic sheen finish",
    catalog_titles: ["B2b Globo Latex Redondo Metal Vinotinto"],
    visual: {
      family: "Metal",
      shape: "round",
      material: "latex",
      color: "burgundy",
      finish: "metallic sheen",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo redondo metal vinotinto", "globo latex redondo metal vinotinto"],
      en: ["round metallic burgundy balloon", "metal burgundy balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20000546", "20000695", "20000863"],
    sizes: { separate: true, allowed_codes: ["R-5", "R-9", "R-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.modeling.latex.reflex.gold",
    canonical_label: "modeling latex balloon in gold with a Reflex high-shine finish",
    visual: {
      family: "Reflex",
      shape: "modeling",
      material: "latex",
      color: "gold",
      finish: "Reflex high-shine",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex tubito reflex dorado", "globo tubito reflex dorado"],
      en: ["tubito reflex gold balloon", "gold reflex tubito balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20014179"],
    sizes: { separate: true, allowed_codes: ["T260"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.modeling.latex.reflex.rose_gold",
    canonical_label: "modeling latex balloon in rose gold with a Reflex high-shine finish",
    visual: {
      family: "Reflex",
      shape: "modeling",
      material: "latex",
      color: "rose gold",
      finish: "Reflex high-shine",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo tubito reflex dorado rosa"],
      en: ["tubito reflex rose gold balloon", "rose gold reflex tubito balloon"],
      contextual: [],
    },
    catalog_product_ids: ["20014181"],
    sizes: { separate: true, allowed_codes: ["T260"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.linkoloon.latex.fashion.white",
    canonical_label: "chain-link Link-O-Loon latex balloon in white, solid Fashion finish",
    catalog_titles: ["GLOBO LINK-O-LOON® FASHION BLANCO", "GLOBO LINK-O-LOONÂ® FASHION BLANCO"],
    visual: {
      family: "Fashion",
      shape: "link-o-loon",
      material: "latex",
      color: "white",
      finish: "Fashion matte",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo latex link o loon fashion blanco", "link o loon blanco"],
      en: ["link-o-loon white balloon", "white link-o-loon balloon", "chain balloon white fashion"],
      contextual: [],
    },
    catalog_product_ids: ["20001063", "20001062", "7109565710529"],
    sizes: { separate: true, allowed_codes: ["LOL-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  // Acá vivía un segundo corazón foil rosado impreso (`balloon.foil.heart.pink`, SKU 30005545,
  // 16 IN, "with printed text"). Se fusionó en `balloon.heart.foil.pink.printed_text`, que es
  // el mismo objeto visual: dos SKUs de corazón rosado con texto impreso, y el texto no puede
  // entrar en el caption, así que para captionar son un solo concepto. Su alias
  // "globo metalizado corazon rosado" era además el título del corazón LISO (SKU 30005444) y
  // se quitó: ese id ahora le corresponde al liso.
  {
    concept_id: "balloon.heart.foil.silver",
    canonical_label: "heart-shaped foil balloon in silver",
    visual: {
      family: "Metalizado",
      shape: "heart",
      material: "foil",
      color: "silver",
      finish: "metallic sheen",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo metalizado corazon plata"],
      en: ["foil heart balloon silver", "silver heart foil balloon"],
      contextual: [],
    },
    catalog_product_ids: ["30005446"],
    sizes: { separate: true, allowed_codes: ["18 IN"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.star.foil.blue",
    canonical_label: "star-shaped foil balloon in blue with a metallic sheen finish",
    visual: {
      family: "Metalizado",
      shape: "star",
      material: "foil",
      color: "blue",
      finish: "metallic sheen",
      pattern: { kind: "solid" },
    },
    aliases: {
      es: ["globo metalizado estrella azul"],
      en: ["foil star balloon blue", "blue star foil balloon"],
      contextual: [],
    },
    catalog_product_ids: ["30005537"],
    sizes: { separate: true, allowed_codes: ["18 IN"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.latex.reflex.gold.printed_christmas",
    canonical_label: "round latex balloon in gold with a Reflex high-shine printed Christmas pattern",
    catalog_titles: ["GLOBO FELIZ NAVIDAD INVIERNO DORADO REFLEX"],
    visual: {
      family: "Reflex",
      shape: "round",
      material: "latex",
      color: "gold",
      finish: "Reflex high-shine",
      pattern: { kind: "printed", motif: "Christmas", contains_text: true },
    },
    aliases: {
      es: ["globo feliz navidad invierno dorado reflex"],
      en: ["gold Reflex Christmas balloon"],
      contextual: [{ value: "dorado", required_tokens: ["reflex", "navidad"] }],
    },
    catalog_product_ids: ["10648772575425"],
    sizes: { separate: true, allowed_codes: ["R-12"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.heart.foil.pink.printed_text",
    canonical_label: "heart-shaped foil balloon in pink with a metallic sheen printed-text pattern",
    // Absorbe el SKU 30005545, que estaba como un concepto aparte con id `foil.heart.pink`:
    // otro corazón rosado con texto impreso. El texto literal no entra al caption, así que
    // los dos SKUs son el mismo objeto visual.
    catalog_titles: ["GLOBO METALIZADO CORAZON ROSADO I LOVE YOU", "GLOBO METALIZADO CORAZON ROSADO CON TEXTO"],
    visual: {
      family: "Metalizado",
      shape: "heart",
      material: "foil",
      color: "pink",
      finish: "metallic sheen",
      pattern: { kind: "printed", motif: "celebratory message", contains_text: true },
    },
    aliases: {
      es: ["globo metalizado corazon rosado con texto"],
      en: ["pink foil heart with printed text"],
      contextual: [],
    },
    catalog_product_ids: ["7105908244673", "30005545"],
    sizes: { separate: true, allowed_codes: ["16 IN", "18 IN"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.round.foil.fuchsia.printed_hearts",
    canonical_label: "round foil balloon in fuchsia with a metallic sheen hearts pattern",
    catalog_titles: ["GLOBO METALIZADO CORAZONES FUCSIA"],
    visual: {
      family: "Metalizado",
      shape: "round",
      material: "foil",
      color: "fuchsia",
      finish: "metallic sheen",
      pattern: { kind: "printed", motif: "hearts", contains_text: false },
    },
    aliases: {
      es: ["globo metalizado corazones fucsia"],
      en: ["fuchsia foil balloon with hearts"],
      contextual: [],
    },
    catalog_product_ids: ["7105908572353"],
    sizes: { separate: true, allowed_codes: ["18 IN"] },
    status: "active",
    vocabulary_version: VOCABULARY_VERSION,
  },
  {
    concept_id: "balloon.foil.chrome.pending",
    canonical_label: "pending catalog foil balloon concept",
    visual: {
      family: "foil",
      shape: "unknown",
      material: "foil",
      color: "unknown",
      finish: "chrome",
      pattern: { kind: "unknown" },
    },
    aliases: { es: [], en: [], contextual: [] },
    catalog_product_ids: [],
    sizes: { separate: true, allowed_codes: [] },
    status: "pending",
    vocabulary_version: VOCABULARY_VERSION,
  },
  ...V007_DATASET_PRODUCT_CONCEPTS,
  ...CATALOG_PRODUCT_CONCEPTS,
];
