import type { GloboDecoracion } from "./decoraciones";
import type { ProductoDePieza } from "./escenografia";
import { TINTA, cara, estampadoDeImpreso, icono, impreso, patron, texto, type ImpresoGlobo } from "./estampados";
import type { MaterialDecoracion } from "./figuras";
import type { Vec3 } from "./modulos";

/**
 * **Globos impresos de la tienda Sempertex** que usan las «Ideas de fiesta» de sempertex.com (los 75 de
 * `productos.json` del barrido del blog): nombre y url exactos, el formato en que se usan (y las tallas que vende la
 * tienda, de las opciones del producto en su listado público /products.json, 2026-10-07), el color base con su código
 * oficial (o los colores del surtido) y el impreso (`estampados.ts`) que mejor lo representa, mirando la foto de cada
 * producto. No se guardan imágenes: el impreso es un dibujo propio, aproximado.
 *
 * Correcciones al mapeo de las ideas (que deducía el formato del nombre): los «corazones» Infinity son redondos R-12,
 * no C-12 (lo dice la url, «latex-redondo», y la talla de la tienda); el único corazón C-12 es «CORAZON 2 CARAS LOVE».
 * Cada fila dice en `nota` lo que el dibujo no copia.
 *
 * Una **pieza** lleva impresos con `impresos` (ver `piezas.ts`): se eligen sus globos por color (todos, o uno de
 * cada `cada`) o por índice; esos globos toman el color base del impreso (salvo en un surtido, donde se queda el suyo),
 * su estampado y su `frente` (hacia +z, el salón), y la pieza lista el producto de la tienda con su cantidad.
 */
export type ImpresoCatalogo = {
  /** La url sin «/products/» ni el prefijo «globo-para-fiesta-latex-redondo-». */
  id: string;
  /** Nombre exacto del producto en la tienda. */
  nombre: string;
  /** Url relativa del producto (/products/…). */
  url: string;
  /** Formato en que lo usan las ideas (R-12 casi siempre). */
  formatoId: string;
  /** Tallas que vende la tienda de este producto. */
  tallas: readonly string[];
  /** Código oficial del color del globo (en un surtido, el primero). */
  codigoBase: string;
  /** Colores del surtido (códigos oficiales, aproximados a la foto); null si es de un solo color. */
  surtido: readonly string[] | null;
  /** «infinity»: impreso alrededor; «2 caras»: delante y detrás; «1 cara». */
  caras: "infinity" | "2 caras" | "1 cara";
  /** En cuántas ideas aparece. */
  ideas: number;
  estampado: ImpresoGlobo;
  /** Impreso distinto según el color del globo (la tinta roja en el blanco y blanca en el rojo). */
  porColor?: Readonly<Record<string, ImpresoGlobo>>;
  nota?: string;
};

// <datos> (generado: no editar a mano entre estas marcas)
export const IMPRESOS_TIENDA: readonly ImpresoCatalogo[] = [
  { id: "infinity-balon-de-futbol-fashion-blanco", nombre: "GLOBO INFINITY® BALÓN DE FUTBOL", url: "/products/globo-para-fiesta-latex-redondo-infinity-balon-de-futbol-fashion-blanco", formatoId: "R-12", tallas: ["R-5", "R-12", "R-24", "R-36"], codigoBase: "005", surtido: null, caras: "infinity", ideas: 13, estampado: impreso([patron("balon", [TINTA.negro], 12, 44)]), nota: "La tienda lo vende en R-5, R-12, R-24 y R-36; aquí R-12." },
  { id: "infinity-graffiti-invierno-fashion-transparente", nombre: "GLOBO REDONDO INFINITY® GRAFFITI INVIERNO FASHION TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-graffiti-invierno-fashion-transparente", formatoId: "R-12", tallas: ["R-12"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 7, estampado: impreso([patron("graffiti", [TINTA.blanco, TINTA.plata], 8, 10)]), nota: "Escarcha blanca en remolinos sobre cristal." },
  { id: "infinity-corazones-modernos-fashion-surtido", nombre: "GLOBO REDONDO INFINITY® CORAZONES MODERNOS", url: "/products/globo-para-fiesta-latex-redondo-infinity-corazones-modernos-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "009", surtido: ["009", "012", "011", "051"], caras: "infinity", ideas: 6, estampado: impreso([patron("corazon", [TINTA.blanco], 6, 38), patron("corazon", [TINTA.blanco], 12, 10, 4)]), nota: "Es redondo (R-12): el mapeo de las ideas lo daba como C-12 por la palabra «corazones»." },
  { id: "infinity-feliz-navidad-dorada-fashion-blanco", nombre: "GLOBO REDONDO INFINITY® FELIZ NAVIDAD DORADA FASHION BLANCO", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-navidad-dorada-fashion-blanco", formatoId: "R-12", tallas: ["R-12"], codigoBase: "005", surtido: null, caras: "infinity", ideas: 6, estampado: impreso([patron("hoja", [TINTA.dorado], 10, 9), texto("Feliz\nNavidad", TINTA.dorado, { letra: "manuscrita", altoGrados: 15 })], 2) },
  { id: "infinity-corazones-brillantes-fashion-metal-surtido", nombre: "GLOBO REDONDO INFINITY® CORAZONES BRILLANTES", url: "/products/globo-para-fiesta-latex-redondo-infinity-corazones-brillantes-fashion-metal-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "009", surtido: ["009", "568", "570", "409"], caras: "infinity", ideas: 5, estampado: impreso([patron("corazon", [TINTA.blanco], 8, 20), patron("destello", [TINTA.blanco], 10, 7, 9)]), nota: "Redondo (R-12), no C-12." },
  { id: "2-caras-feliz-dia-fiesta-bigotes-reflex-surtido", nombre: "GLOBO REFLEX FELIZ DIA FIESTA BIGOTES", url: "/products/globo-latex-redondo-2-caras-feliz-dia-fiesta-bigotes-reflex-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "940", surtido: ["940", "981", "970"], caras: "2 caras", ideas: 5, estampado: impreso([icono("bigote", TINTA.blanco, { tamanoGrados: 34, dyGrados: 30 }), texto("Feliz\nDÍA", TINTA.blanco, { letra: "bloque", altoGrados: 17, dyGrados: -6 })], 2) },
  { id: "infinity-graffiti-invierno-fashion-rojo", nombre: "GLOBO REDONDO INFINITY® GRAFFITI INVIERNO FASHION ROJO", url: "/products/globo-para-fiesta-latex-redondo-infinity-graffiti-invierno-fashion-rojo", formatoId: "R-12", tallas: ["R-12"], codigoBase: "015", surtido: null, caras: "infinity", ideas: 4, estampado: impreso([patron("graffiti", [TINTA.blanco], 8, 10)]) },
  { id: "infinity-love-fashion-surtido", nombre: "GLOBO REDONDO INFINITY® LOVE FASHION SURTIDO", url: "/products/globo-para-fiesta-latex-redondo-infinity-love-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "015", surtido: ["015", "009", "012"], caras: "infinity", ideas: 3, estampado: impreso([patron("splash", [TINTA.blanco], 8, 12, 5), icono("corazon", TINTA.blanco, { tamanoGrados: 70 }), texto("LOVE", TINTA.rojo, { letra: "bloque", altoGrados: 15, anchoMaxGrados: 48 })], 2), nota: "El «LOVE» va dentro de un corazón blanco, con garabatos blancos alrededor." },
  { id: "2-caras-happy-halloween-noche-reflex-surtido", nombre: "GLOBO REDONDO HAPPY HALLOWEEN", url: "/products/globo-para-fiesta-latex-redondo-2-caras-happy-halloween-noche-reflex-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "931", surtido: ["931", "951", "981"], caras: "2 caras", ideas: 3, estampado: impreso([texto("HAPPY\nHALLOWEEN", TINTA.negro, { letra: "bloque", altoGrados: 15 }), icono("calabaza", TINTA.negro, { tamanoGrados: 18, dyGrados: 30, tinta2: TINTA.negro })], 2), nota: "Los murciélagos de la tienda no se dibujan: va una calabacita." },
  { id: "infinity-arana-fashion-transparente", nombre: "GLOBO INFINITY® ARAÑA TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-arana-fashion-transparente", formatoId: "R-12", tallas: ["R-12"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 3, estampado: impreso([patron("telarana", [TINTA.negro], 6, 30), patron("arana", [TINTA.negro], 7, 10, 3)]) },
  { id: "infinity-metalink-plata-graffiti-fashion-negro", nombre: "GLOBO REDONDO INFINITY® METALINK PLATA GRAFFITI FASHION NEGRO", url: "/products/globo-para-fiesta-latex-redondo-infinity-metalink-plata-graffiti-fashion-negro", formatoId: "R-12", tallas: ["R-12"], codigoBase: "080", surtido: null, caras: "infinity", ideas: 3, estampado: impreso([patron("graffiti", [TINTA.plata, TINTA.blanco], 8, 10)]) },
  { id: "fashion-surtido-navidad-rojo-y-verde-selva", nombre: "GLOBO FASHION SURTIDO NAVIDAD", url: "/products/globo-para-fiesta-latex-redondo-fashion-surtido-navidad-rojo-y-verde-selva", formatoId: "R-12", tallas: ["R-9", "R-12"], codigoBase: "015", surtido: ["015", "032"], caras: "1 cara", ideas: 3, estampado: impreso([icono("flor", TINTA.blanco, { tamanoGrados: 16, dyGrados: -58, tinta2: TINTA.blanco })]), nota: "Liso rojo y verde con una florecita blanca cerca del cuello." },
  { id: "infinity-feliz-dia-mama-corazones-fashion-surtido-rojo-blanco", nombre: "GLOBO REDONDO INFINITY® FELIZ DIA MAMA CORAZONES FASHION SURTIDO ROJO - BLANCO", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-dia-mama-corazones-fashion-surtido-rojo-blanco", formatoId: "R-12", tallas: ["R-12"], codigoBase: "005", surtido: ["005", "015"], caras: "infinity", ideas: 2, estampado: impreso([patron("corazon", [TINTA.rojo], 13, 8), texto("Feliz\nDía\nMamá", TINTA.rojo, { letra: "bloque", altoGrados: 14 })], 2), porColor: { "015": impreso([patron("corazon", [TINTA.blanco], 13, 8), texto("Feliz\nDía\nMamá", TINTA.blanco, { letra: "bloque", altoGrados: 14 })], 2) }, nota: "Redondo (R-12), no C-12. En el blanco la tinta es roja; en el rojo, blanca." },
  { id: "infinity-feliz-ano-estrellas-satin-y-metal-surtido-deluxe", nombre: "GLOBO REDONDO INFINITY® FELIZ AÑO ESTRELLAS", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-ano-estrellas-satin-y-metal-surtido-deluxe", formatoId: "R-12", tallas: ["R-12"], codigoBase: "570", surtido: ["570", "080", "481"], caras: "infinity", ideas: 2, estampado: impreso([patron("estrella", [TINTA.blanco], 14, 6), texto("FELIZ", TINTA.blanco, { letra: "bloque", altoGrados: 15, dyGrados: 10 }), texto("Año", TINTA.blanco, { letra: "manuscrita", altoGrados: 17, dyGrados: -10 })], 2) },
  { id: "infinity-bigotes-y-corbatines-fashion-transparente", nombre: "GLOBO INFINITY® BIGOTES Y CORBATINES CRISTAL", url: "/products/globo-para-fiesta-latex-redondo-infinity-bigotes-y-corbatines-fashion-transparente", formatoId: "R-12", tallas: ["R-12"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("bigote", [TINTA.negro], 7, 16), patron("corbatin", [TINTA.negro], 6, 14, 5)]) },
  { id: "infinity-feliz-cumpleanos-terrazo-azul-fashion-surtido", nombre: "GLOBO LATEX REDONDO INFINITY® FELIZ CUMPLEAÑOS TERRAZO AZUL FASHION SURTIDO", url: "/products/globo-latex-redondo-infinity-feliz-cumpleanos-terrazo-azul-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "042", surtido: ["042", "041", "044"], caras: "infinity", ideas: 2, estampado: impreso([patron("terrazo", [TINTA.blanco, TINTA.azulCielo], 9, 12), texto("FELIZ", TINTA.blanco, { letra: "redonda", altoGrados: 16, dyGrados: 10 }), texto("Cumpleaños", TINTA.blanco, { letra: "manuscrita", altoGrados: 13, dyGrados: -8 })], 2) },
  { id: "infinity-animal-print-fashion-y-metal-surtido", nombre: "GLOBO REDONDO INFINITY® ANIMAL PRINT", url: "/products/globo-para-fiesta-latex-redondo-infinity-animal-print-fashion-y-metal-surtido", formatoId: "R-12", tallas: ["R-5", "R-12"], codigoBase: "071", surtido: ["071", "570", "080"], caras: "infinity", ideas: 2, estampado: impreso([patron("animal", [TINTA.cafe, TINTA.negro], 8, 18)]), nota: "Jirafa y leopardo: manchas irregulares." },
  { id: "2-caras-monstruos-fashion-surtido", nombre: "GLOBO REDONDO 2 CARAS MONSTRUOS FASHION SURTIDO", url: "/products/globo-para-fiesta-latex-redondo-2-caras-monstruos-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "031", surtido: ["031", "051", "061", "080"], caras: "2 caras", ideas: 2, estampado: impreso([cara("monstruo", TINTA.blanco, { anchoGrados: 110 })], 2) },
  { id: "infinity-feliz-dia-bigotes-fashion-surtido", nombre: "GLOBO REDONDO INFINITY® FELIZ DIA BIGOTES FASHION SURTIDO", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-dia-bigotes-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "040", surtido: ["040", "041", "080"], caras: "infinity", ideas: 2, estampado: impreso([patron("bigote", [TINTA.blanco], 10, 9), texto("Feliz Día", TINTA.blanco, { letra: "manuscrita", altoGrados: 15 })], 2) },
  { id: "corazon-2-caras-love-fashion-rojo", nombre: "GLOBO CORAZON 2 CARAS LOVE FASHION ROJO", url: "/products/globo-para-fiesta-latex-corazon-2-caras-love-fashion-rojo", formatoId: "C-12", tallas: ["C-12"], codigoBase: "015", surtido: null, caras: "2 caras", ideas: 2, estampado: impreso([texto("LO\nVE", TINTA.blanco, { letra: "bloque", altoGrados: 22 })], 2) },
  { id: "infinity-feliz-dia-corazones-brillantes-metal-surtido", nombre: "GLOBO REDONDO INFINITY® FELIZ DÍA CORAZONES BRILLANTES METAL SURTIDO", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-dia-corazones-brillantes-metal-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "515", surtido: ["515", "570"], caras: "infinity", ideas: 2, estampado: impreso([patron("corazon", [TINTA.blanco], 11, 8), texto("Feliz\nDía", TINTA.blanco, { letra: "manuscrita", altoGrados: 16 })], 2), nota: "Redondo (R-12), no C-12." },
  { id: "infinity-balon-de-futbol-fashion-surtido", nombre: "GLOBO INFINITY® BALÓN DE FUTBOL", url: "/products/globo-para-fiesta-latex-redondo-infinity-balon-de-futbol-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "015", surtido: ["015", "020", "031", "040", "061"], caras: "infinity", ideas: 2, estampado: impreso([patron("balon", [TINTA.negro], 12, 44)]) },
  { id: "infinity-estrellas-fashion-transparente", nombre: "GLOBO REDONDO INFINITY® ESTRELLAS FASHION TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-estrellas-fashion-transparente", formatoId: "R-12", tallas: ["R-5", "R-12", "R-24"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("estrella", [TINTA.blanco], 16, 7)]), nota: "La tienda lo vende en R-5, R-12 y R-24." },
  { id: "infinity-graffiti-rosa-fashion-transparente", nombre: "GLOBO REDONDO INFINITY® GRAFFITI ROSA FASHION TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-graffiti-rosa-fashion-transparente", formatoId: "R-12", tallas: ["R-12"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("graffiti", [TINTA.rosado, TINTA.fucsia], 8, 11)]) },
  { id: "infinity-polka-blanco-fashion-verde-lima", nombre: "GLOBO REDONDO INFINITY® POLKA BLANCO FASHION VERDE LIMA", url: "/products/globo-para-fiesta-latex-redondo-infinity-polka-blanco-fashion-verde-lima", formatoId: "R-12", tallas: ["R-12"], codigoBase: "031", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("punto", [TINTA.blanco], 7, 15)]) },
  { id: "infinity-graffiti-cielo-fashion-transparente", nombre: "GLOBO REDONDO INFINITY® GRAFFITI CIELO FASHION TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-graffiti-cielo-fashion-transparente", formatoId: "R-12", tallas: ["R-12"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("graffiti", [TINTA.azulCielo, TINTA.blanco], 8, 12)]) },
  { id: "infinity-polka-blanco-fashion-rojo", nombre: "GLOBO REDONDO INFINITY® POLKA BLANCO FASHION ROJO", url: "/products/globo-para-fiesta-latex-redondo-infinity-polka-blanco-fashion-rojo", formatoId: "R-12", tallas: ["R-12"], codigoBase: "015", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("punto", [TINTA.blanco], 7, 15)]) },
  { id: "infinity-feliz-dia-fiesta-bigotes-fashion-surtido", nombre: "GLOBO REDONDO INFINITY®FELIZ DIA FIESTA BIGOTES", url: "/products/globo-latex-redondo-infinity-feliz-dia-fiesta-bigotes-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "041", surtido: ["041", "020", "074", "040"], caras: "infinity", ideas: 2, estampado: impreso([patron("confeti", [TINTA.blanco], 12, 8), icono("bigote", TINTA.blanco, { tamanoGrados: 30, dyGrados: 28 }), texto("Feliz\nDÍA", TINTA.blanco, { letra: "bloque", altoGrados: 16, dyGrados: -6 })], 2) },
  { id: "infinity-confetti-dorado-fashion-transparente", nombre: "GLOBO INFINITY® CONFETTI DORADO TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-confetti-dorado-fashion-transparente", formatoId: "R-12", tallas: ["R-12"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("punto", [TINTA.dorado], 18, 4.5)]) },
  { id: "infinity-estrellas-reflex-plata", nombre: "GLOBO REDONDO INFINITY® ESTRELLAS REFLEX PLATA", url: "/products/globo-para-fiesta-latex-redondo-infinity-estrellas-reflex-plata", formatoId: "R-5", tallas: ["R-5"], codigoBase: "981", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("estrella", [TINTA.blanco], 12, 9)]), nota: "La tienda lo vende en R-5 (el mapeo de las ideas decía R-12)." },
  { id: "2-caras-feliz-cumpleanos-fiesta-destellos-reflex-surtido", nombre: "GLOBO FELIZ CUMPLEAÑOS DESTELLOS", url: "/products/globo-para-fiesta-latex-redondo-2-caras-feliz-cumpleanos-fiesta-destellos-reflex-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "909", surtido: ["909", "951", "970"], caras: "2 caras", ideas: 2, estampado: impreso([texto("FELIZ", TINTA.blanco, { letra: "bloque", altoGrados: 16, dyGrados: 10 }), texto("Cumpleaños", TINTA.blanco, { letra: "manuscrita", altoGrados: 13, dyGrados: -8 })], 2) },
  { id: "infinity-corazones-por-siempre-fashion-surtido-rojo-blanco", nombre: "GLOBO REDONDO INFINITY® CORAZONES POR SIEMPRE FASHION SURTIDO ROJO - BLANCO", url: "/products/globo-para-fiesta-latex-redondo-infinity-corazones-por-siempre-fashion-surtido-rojo-blanco", formatoId: "R-12", tallas: ["R-12"], codigoBase: "005", surtido: ["005", "015"], caras: "infinity", ideas: 2, estampado: impreso([patron("corazon", [TINTA.rojo], 12, 9)]), porColor: { "015": impreso([patron("corazon", [TINTA.blanco], 12, 9)]) }, nota: "Redondo (R-12), no C-12. Corazones rojos sobre blanco y blancos sobre rojo." },
  { id: "infinity-graffiti-marmol-fashion-transparente", nombre: "GLOBO REDONDO INFINITY® GRAFFITI MARMOL FASHION TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-graffiti-marmol-fashion-transparente", formatoId: "R-12", tallas: ["R-12"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("graffiti", [TINTA.plata, TINTA.gris], 8, 11)]) },
  { id: "infinity-arana-metalink-fashion-negro", nombre: "GLOBO INFINITY® ARAÑA METALINK", url: "/products/globo-para-fiesta-latex-redondo-infinity-arana-metalink-fashion-negro", formatoId: "R-12", tallas: ["R-12"], codigoBase: "080", surtido: null, caras: "infinity", ideas: 2, estampado: impreso([patron("telarana", [TINTA.plata], 6, 30), patron("arana", [TINTA.plata], 7, 10, 3)]) },
  { id: "infinity-corazones-surtidos-fashion-y-metal-surtido", nombre: "GLOBO REDONDO INFINITY® CORAZONES SURTIDOS", url: "/products/globo-para-fiesta-latex-redondo-infinity-corazones-surtidos-fashion-y-metal-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "009", surtido: ["009", "012", "015", "570"], caras: "infinity", ideas: 2, estampado: impreso([patron("corazon", [TINTA.blanco], 9, 16)]), nota: "Redondo (R-12), no C-12." },
  { id: "2-caras-happy-halloween-fashion-surtido-negro-naranja", nombre: "GLOBO REDONDO HAPPY HALLOWEEN", url: "/products/globo-para-fiesta-latex-redondo-2-caras-happy-halloween-fashion-surtido-negro-naranja", formatoId: "R-12", tallas: ["R-12"], codigoBase: "061", surtido: ["061", "080"], caras: "2 caras", ideas: 2, estampado: impreso([texto("HAPPY\nHALLOWEEN", TINTA.negro, { letra: "bloque", altoGrados: 15 }), icono("calabaza", TINTA.negro, { tamanoGrados: 18, dyGrados: 30, tinta2: TINTA.negro })], 2), porColor: { "080": impreso([texto("HAPPY\nHALLOWEEN", TINTA.naranja, { letra: "bloque", altoGrados: 15 }), icono("calabaza", TINTA.naranja, { tamanoGrados: 18, dyGrados: 30, tinta2: TINTA.naranja })], 2) } },
  { id: "infinity-es-una-nina-estrella-pastel-mate-rosado", nombre: "GLOBO INFINITY® ES UNA NIÑA ESTRELLA", url: "/products/globo-para-fiesta-latex-redondo-infinity-es-una-nina-estrella-pastel-mate-rosado", formatoId: "R-12", tallas: ["R-12"], codigoBase: "609", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([icono("estrella", TINTA.blanco, { tamanoGrados: 16, dxGrados: 22, dyGrados: 20 }), texto("es una\nNiña", TINTA.blanco, { letra: "redonda", altoGrados: 16 })], 2) },
  { id: "infinity-es-un-nino-estrella-pastel-mate-azul", nombre: "GLOBO INFINITY® ES UN NIÑO ESTRELLA", url: "/products/globo-para-fiesta-latex-redondo-infinity-es-un-nino-estrella-pastel-mate-azul", formatoId: "R-12", tallas: ["R-12"], codigoBase: "640", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([icono("estrella", TINTA.blanco, { tamanoGrados: 16, dxGrados: 22, dyGrados: 20 }), texto("es un\nNiño", TINTA.blanco, { letra: "redonda", altoGrados: 16 })], 2) },
  { id: "infinity-r-corazones-brillantes-fashion-surtido", nombre: "GLOBO REDONDO INFINITY® CORAZONES BRILLANTES", url: "/products/globo-latex-redondo-infinity-r-corazones-brillantes-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "015", surtido: ["015", "012", "009"], caras: "infinity", ideas: 1, estampado: impreso([patron("corazon", [TINTA.blanco], 11, 8), texto("Feliz\nDía", TINTA.blanco, { letra: "manuscrita", altoGrados: 16 })], 2), nota: "Redondo (R-12), no C-12: corazones con «Feliz Día»." },
  { id: "infinity-feliz-dia-mami-flores-fashion-surtido-rojo-blanco", nombre: "GLOBO LATEX REDONDO INFINITY® FELIZ DIA MAMI FLORES FASHION SURTIDO ROJO - BLANCO", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-dia-mami-flores-fashion-surtido-rojo-blanco", formatoId: "R-12", tallas: ["R-12"], codigoBase: "005", surtido: ["005", "015"], caras: "infinity", ideas: 1, estampado: impreso([patron("flor", [TINTA.rojo], 11, 9), texto("Feliz Día\nMami", TINTA.rojo, { letra: "redonda", altoGrados: 14 })], 2), porColor: { "015": impreso([patron("flor", [TINTA.blanco], 11, 9), texto("Feliz Día\nMami", TINTA.blanco, { letra: "redonda", altoGrados: 14 })], 2) } },
  { id: "2-caras-feliz-ano-estrellas-reflex-surtido", nombre: "GLOBO REDONDO FELIZ AÑO ESTRELLAS", url: "/products/globo-para-fiesta-latex-redondo-2-caras-feliz-ano-estrellas-reflex-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "981", surtido: ["981", "970"], caras: "2 caras", ideas: 1, estampado: impreso([patron("destello", [TINTA.blanco], 12, 6), texto("Feliz\nAño", TINTA.blanco, { letra: "manuscrita", altoGrados: 17 })], 2) },
  { id: "infinity-feliz-ano-estrellas-fashion-negro", nombre: "GLOBO REDONDO INFINITY® FELIZ AÑO ESTRELLAS FASHION NEGRO", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-ano-estrellas-fashion-negro", formatoId: "R-24", tallas: ["R-24"], codigoBase: "080", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("destello", [TINTA.dorado], 12, 6), texto("Feliz\nAño", TINTA.dorado, { letra: "manuscrita", altoGrados: 16 })], 3), nota: "La tienda lo vende en R-24 (paquete de 3)." },
  { id: "infinity-paraiso-tropical-fashion-surtido", nombre: "GLOBO REDONDO INFINITY®PARAISO TROPICAL FASHION SURTIDO", url: "/products/globo-latex-redondo-infinity-paraiso-tropical-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "056", surtido: ["056", "059", "061"], caras: "infinity", ideas: 1, estampado: impreso([patron("hoja", [TINTA.blanco], 7, 26), patron("flor", [TINTA.blanco], 8, 10, 6)]) },
  { id: "infinity-corazones-por-siempre-fashion-rojo", nombre: "GLOBO REDONDO INFINITY® CORAZONES POR SIEMPRE FASHION ROJO", url: "/products/globo-para-fiesta-latex-redondo-infinity-corazones-por-siempre-fashion-rojo", formatoId: "R-12", tallas: ["R-12"], codigoBase: "015", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("corazon", [TINTA.blanco], 12, 9)]), nota: "Redondo (R-12), no C-12." },
  { id: "infinity-feliz-cumpleanos-terrazo-azul-fashion", nombre: "GLOBO REDONDO INFINITY® TERRAZO AZUL FASHION SURTIDO", url: "/products/globo-latex-redondo-infinity-feliz-cumpleanos-terrazo-azul-fashion", formatoId: "R-12", tallas: ["R-12"], codigoBase: "044", surtido: ["044", "041", "042"], caras: "infinity", ideas: 1, estampado: impreso([patron("terrazo", [TINTA.blanco, TINTA.azulCielo], 9, 12)]), nota: "Solo el terrazo (sin letrero), pese a lo que dice la url." },
  { id: "2-caras-feliz-dia-bigotes-reflex-surtido", nombre: "GLOBO LATEX REDONDO 2 CARAS FELIZ DIA BIGOTES REFLEX SURTIDO", url: "/products/globo-para-fiesta-latex-redondo-2-caras-feliz-dia-bigotes-reflex-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "940", surtido: ["940", "981"], caras: "2 caras", ideas: 1, estampado: impreso([icono("bigote", TINTA.blanco, { tamanoGrados: 40, dyGrados: 6 }), texto("Feliz Día", TINTA.blanco, { letra: "manuscrita", altoGrados: 13, dyGrados: -14 })], 2) },
  { id: "infinity-r-feliz-dia-papa-oeste-fashion-surtido", nombre: "GLOBO REDONDO INFINITY® FELIZ DIA PAPA OESTE FASHION SURTIDO", url: "/products/globo-latex-redondo-infinity-r-feliz-dia-papa-oeste-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "041", surtido: ["041", "074", "023"], caras: "infinity", ideas: 1, estampado: impreso([icono("sombrero", TINTA.blanco, { tamanoGrados: 14, dyGrados: 32 }), texto("FELIZ\nDía\nPAPÁ", TINTA.blanco, { letra: "bloque", altoGrados: 13 })], 2), nota: "Del oeste: cactus y herraduras no se dibujan." },
  { id: "infinity-metalink-plata-graffiti-fashion-blanco", nombre: "GLOBO REDONDO INFINITY® METALINK PLATA GRAFFITI FASHION BLANCO", url: "/products/globo-para-fiesta-latex-redondo-infinity-metalink-plata-graffiti-fashion-blanco", formatoId: "R-12", tallas: ["R-12"], codigoBase: "005", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("graffiti", [TINTA.plata], 8, 10)]) },
  { id: "infinity-feliz-cumpleanos-terra-fashion-surtido", nombre: "GLOBO REDONDO INFINITY® FELIZ CUMPLEAÑOS TERRA FASHION SURTIDO", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-cumpleanos-terra-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "023", surtido: ["023", "071", "062", "074"], caras: "infinity", ideas: 1, estampado: impreso([patron("splash", [TINTA.blanco], 7, 12, 8), texto("Feliz\nCumpleaños", TINTA.blanco, { letra: "manuscrita", altoGrados: 14 })], 2) },
  { id: "infinity-mi-primera-comunion-palomas-fashion-blanco", nombre: "GLOBO REDONDO INFINITY® MI PRIMERA COMUNION PALOMAS FASHION BLANCO", url: "/products/globo-para-fiesta-latex-redondo-infinity-mi-primera-comunion-palomas-fashion-blanco", formatoId: "R-12", tallas: ["R-12"], codigoBase: "005", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("paloma", [TINTA.dorado], 9, 10), texto("Mi Primera\nComunión", TINTA.dorado, { letra: "manuscrita", altoGrados: 13 })], 2) },
  { id: "infinity-happy-birthday-diamante-escarchado-dorado-fashion-negro", nombre: "GLOBO REDONDO INFINITY® HAPPY BIRTHDAY DIAMANTE ESCARCHADO DORADO FASHION NEGRO", url: "/products/globo-para-fiesta-latex-redondo-infinity-happy-birthday-diamante-escarchado-dorado-fashion-negro", formatoId: "R-12", tallas: ["R-12"], codigoBase: "080", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("destello", [TINTA.dorado], 11, 7), texto("Happy\nBirthday", TINTA.dorado, { letra: "redonda", altoGrados: 15 })], 2) },
  { id: "infinity-diamantes-cobre-fashion-blanco", nombre: "GLOBO REDONDO INFINITY® DIAMANTES COBRE FASHION BLANCO", url: "/products/globo-para-fiesta-latex-redondo-infinity-diamantes-cobre-fashion-blanco", formatoId: "R-12", tallas: ["R-12"], codigoBase: "005", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("diamante", [TINTA.cobre], 9, 14)]) },
  { id: "infinity-feliz-dia-mami-flores-fashion-surtido-rosa-silvestre", nombre: "GLOBO REDONDO INFINITY® FELIZ DIA MAMI FLORES FASHION SURTIDO ROSA SILVESTRE", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-dia-mami-flores-fashion-surtido-rosa-silvestre", formatoId: "R-12", tallas: ["R-12"], codigoBase: "009", surtido: ["009", "011", "012"], caras: "infinity", ideas: 1, estampado: impreso([patron("flor", [TINTA.blanco], 11, 9), texto("Feliz Día\nMami", TINTA.blanco, { letra: "redonda", altoGrados: 14 })], 2) },
  { id: "2-caras-feliz-cumpleanos-splash-neon-neon-surtido", nombre: "GLOBO REDONDO FELIZ CUMPLEAÑOS SPLASH", url: "/products/globo-para-fiesta-latex-redondo-2-caras-feliz-cumpleanos-splash-neon-neon-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "212", surtido: ["212", "220", "230", "240", "261"], caras: "2 caras", ideas: 1, estampado: impreso([patron("splash", [TINTA.blanco], 6, 10, 2), texto("FELIZ\nCumple\nAÑOS", TINTA.blanco, { letra: "bloque", altoGrados: 13 })], 2) },
  { id: "infinity-feliz-cumpleanos-splash-neon-fashion-transparente", nombre: "GLOBO REDONDO INFINITY® FELIZ CUMPLEAÑOS SPLASH NEON FASHION TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-cumpleanos-splash-neon-fashion-transparente", formatoId: "R-12", tallas: ["R-12"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("splash", [TINTA.amarillo, TINTA.verdeLima, TINTA.azulCielo], 7, 9, 2), texto("FELIZ\nCumple\nAÑOS", TINTA.fucsia, { letra: "bloque", altoGrados: 13 })], 3) },
  { id: "globo-redondo-infinity-futbolmania-blanco", nombre: "GLOBO REDONDO INFINITY FUTBOLMANÍA BLANCO", url: "/products/globo-redondo-infinity-futbolmania-blanco", formatoId: "R-12", tallas: ["R-12"], codigoBase: "005", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([icono("balon", TINTA.negro, { tamanoGrados: 26 }), icono("balon", TINTA.negro, { tamanoGrados: 18, dxGrados: 34, dyGrados: 30 }), icono("balon", TINTA.negro, { tamanoGrados: 18, dxGrados: -34, dyGrados: -30 })], 3), nota: "Balones con estela: aquí los balones, sin la estela." },
  { id: "tubito-2-caras-estrellas-bold-fashion-surtido", nombre: "GLOBO TUBITO 2 CARAS ESTRELLAS BOLD FASHION SURTIDO", url: "/products/globo-para-fiesta-latex-tubito-2-caras-estrellas-bold-fashion-surtido", formatoId: "T-260", tallas: ["T-260"], codigoBase: "015", surtido: ["015", "041", "020", "031", "061", "012"], caras: "2 caras", ideas: 1, estampado: impreso([patron("estrella", [TINTA.blanco], 20, 6)], 2), nota: "Tubito: el visor todavía no pinta impresos sobre tubitos (se ve liso)." },
  { id: "infinity-estrellas-reflex-dorado", nombre: "GLOBO REDONDO INFINITY® ESTRELLAS", url: "/products/globo-para-fiesta-latex-redondo-infinity-estrellas-reflex-dorado", formatoId: "R-5", tallas: ["R-5"], codigoBase: "970", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("estrella", [TINTA.blanco], 12, 9)]), nota: "La tienda lo vende en R-5." },
  { id: "infinity-diamantes-dorados-fashion-transparente", nombre: "GLOBO REDONDO INFINITY® DIAMANTES DORADOS FASHION TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-diamantes-dorados-fashion-transparente", formatoId: "R-24", tallas: ["R-24"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("diamante", [TINTA.dorado], 9, 14)]), nota: "La tienda lo vende en R-24 (paquete de 3)." },
  { id: "infinity-i-love-you-moderno-fashion-rojo", nombre: "GLOBO REDONDO INFINITY® I LOVE YOU MODERNO FASHION ROJO", url: "/products/globo-para-fiesta-latex-redondo-infinity-i-love-you-moderno-fashion-rojo", formatoId: "R-12", tallas: ["R-12"], codigoBase: "015", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([texto("I LOVE\nYOU", TINTA.blanco, { letra: "bloque", altoGrados: 17 }), icono("corazon", TINTA.blanco, { tamanoGrados: 12, dxGrados: 30, dyGrados: -12 })], 3) },
  { id: "infinity-graffiti-dorado-rosa-fashion-blanco", nombre: "GLOBO REDONDO INFINITY® GRAFFITI DORADO ROSA FASHION BLANCO", url: "/products/globo-para-fiesta-latex-redondo-infinity-graffiti-dorado-rosa-fashion-blanco", formatoId: "R-12", tallas: ["R-12"], codigoBase: "005", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("graffiti", [TINTA.doradoRosa], 8, 11)]) },
  { id: "infinity-felicidades-grado-satin-y-metal-surtido", nombre: "GLOBO REDONDO INFINITY® FELICIDADES GRADO", url: "/products/globo-para-fiesta-latex-redondo-infinity-felicidades-grado-satin-y-metal-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "481", surtido: ["481", "570"], caras: "infinity", ideas: 1, estampado: impreso([patron("confeti", [TINTA.negro], 12, 7), icono("birrete", TINTA.negro, { tamanoGrados: 26, dyGrados: 16 }), texto("Felicidades", TINTA.negro, { letra: "manuscrita", altoGrados: 12, dyGrados: -10 })], 2) },
  { id: "2-caras-mensajes-grado-reflex-plata", nombre: "GLOBO REDONDO FELIZ GRADO", url: "/products/globo-para-fiesta-latex-redondo-2-caras-mensajes-grado-reflex-plata", formatoId: "R-12", tallas: ["R-12"], codigoBase: "981", surtido: null, caras: "2 caras", ideas: 1, estampado: impreso([icono("birrete", TINTA.negro, { tamanoGrados: 18, dxGrados: 22, dyGrados: 24 }), texto("Feliz\nGRADO", TINTA.negro, { letra: "bloque", altoGrados: 16 })], 2) },
  { id: "infinity-happy-halloween-friends-fashion-negro", nombre: "GLOBO REDONDO INFINITY® HAPPY HALLOWEEN FRIENDS FASHION NEGRO", url: "/products/globo-latex-redondo-infinity-happy-halloween-friends-fashion-negro", formatoId: "R-12", tallas: ["R-12"], codigoBase: "080", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([icono("calabaza", TINTA.naranja, { tamanoGrados: 50, dyGrados: 8, tinta2: TINTA.verde }), texto("Happy\nHalloween", TINTA.blanco, { letra: "manuscrita", altoGrados: 9, dyGrados: 6 })]) },
  { id: "infinity-happy-halloween-noche-fashion-surtido", nombre: "GLOBO INFINITY® HAPPY HALLOWEEN", url: "/products/globo-para-fiesta-latex-redondo-infinity-happy-halloween-noche-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "031", surtido: ["031", "051", "061"], caras: "infinity", ideas: 1, estampado: impreso([patron("arana", [TINTA.negro], 9, 8, 6), texto("HAPPY\nHALLOWEEN", TINTA.negro, { letra: "bloque", altoGrados: 15 })], 2), nota: "Los murciélagos de la tienda van como arañitas." },
  { id: "infinity-hojas-tropicales-fashion-negro", nombre: "GLOBO REDONDO INFINITY® HOJAS TROPICALES FASHION NEGRO", url: "/products/globo-para-fiesta-latex-redondo-infinity-hojas-tropicales-fashion-negro", formatoId: "R-12", tallas: ["R-12"], codigoBase: "080", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("hoja", [TINTA.dorado], 7, 24)]) },
  { id: "infinity-feliz-cumpleanos-mrmld-rosa-silk-surtido", nombre: "GLOBO REDONDO INFINITY® FELIZ CUMPLEAÑOS MARBLE ROSA SILK SURTIDO", url: "/products/globo-latex-redondo-infinity-feliz-cumpleanos-mrmld-rosa-silk-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "809", surtido: ["809", "850", "870"], caras: "infinity", ideas: 1, estampado: impreso([patron("marmol", [TINTA.blanco], 6, 14), texto("Feliz\nCumpleaños", TINTA.blanco, { letra: "manuscrita", altoGrados: 14 })], 2) },
  { id: "infinity-r-happy-birthday-marble-rosa-silk-surtido-copia", nombre: "GLOBO REDONDO INFINITY® FELIZ CUMPLEAÑOS MARIPOSAS SILK SURTIDO", url: "/products/globo-latex-redondo-infinity-r-happy-birthday-marble-rosa-silk-surtido-copia", formatoId: "R-12", tallas: ["R-12"], codigoBase: "809", surtido: ["809", "826", "839", "850"], caras: "infinity", ideas: 1, estampado: impreso([patron("mariposa", [TINTA.blanco], 8, 12), texto("FELIZ", TINTA.blanco, { letra: "redonda", altoGrados: 16, dyGrados: 10 }), texto("Cumpleaños", TINTA.blanco, { letra: "manuscrita", altoGrados: 13, dyGrados: -8 })], 2), nota: "Mariposas (la url dice «marble», el producto es «Mariposas»)." },
  { id: "infinity-feliz-navidad-corona-fashion-surtido-navidad", nombre: "GLOBO REDONDO INFINITY® FELIZ NAVIDAD CORONA FASHION SURTIDO NAVIDAD", url: "/products/globo-para-fiesta-latex-redondo-infinity-feliz-navidad-corona-fashion-surtido-navidad", formatoId: "R-12", tallas: ["R-12"], codigoBase: "015", surtido: ["015", "032"], caras: "infinity", ideas: 1, estampado: impreso([patron("copo", [TINTA.blanco], 10, 9), texto("FELIZ", TINTA.blanco, { letra: "bloque", altoGrados: 13, dyGrados: 12 }), texto("Navidad", TINTA.blanco, { letra: "manuscrita", altoGrados: 16, dyGrados: -8 })], 2) },
  { id: "2-caras-navidad-brillante-reflex-surtido", nombre: "GLOBO REDONDO NAVIDAD BRILLANTE", url: "/products/globo-para-fiesta-latex-redondo-2-caras-navidad-brillante-reflex-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "915", surtido: ["915", "981"], caras: "2 caras", ideas: 1, estampado: impreso([patron("destello", [TINTA.blanco], 10, 6), texto("¡Feliz\nNavidad!", TINTA.blanco, { letra: "manuscrita", altoGrados: 15 })], 2) },
  { id: "infinity-confetti-multicolor-pastel-fashion-transparente", nombre: "GLOBO LATEX REDONDO INFINITY® CONFETTI MULTICOLOR PASTEL FASHION TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-confetti-multicolor-pastel-fashion-transparente", formatoId: "R-5", tallas: ["R-5", "R-12"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("confeti", [TINTA.rosado, TINTA.lila, TINTA.azulCielo, TINTA.amarillo], 12, 10)]), nota: "Las ideas lo usan en R-5; la tienda también lo vende en R-12." },
  { id: "infinity-palomas-fashion-transparente", nombre: "GLOBO REDONDO INFINITY® PALOMAS FASHION TRANSPARENTE", url: "/products/globo-para-fiesta-latex-redondo-infinity-palomas-fashion-transparente", formatoId: "R-12", tallas: ["R-12", "R-24"], codigoBase: "390", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("paloma", [TINTA.blanco], 7, 16)]), nota: "La tienda lo vende en R-12 y R-24." },
  { id: "infinity-interrogacion-fashion-negro", nombre: "GLOBO REDONDO INFINITY® INTERROGACION FASHION NEGRO", url: "/products/globo-para-fiesta-latex-redondo-infinity-interrogacion-fashion-negro", formatoId: "R-36", tallas: ["R-36"], codigoBase: "080", surtido: null, caras: "infinity", ideas: 1, estampado: impreso([patron("interrogacion", [TINTA.blanco], 9, 14), icono("interrogacion", TINTA.blanco, { tamanoGrados: 40 })]), nota: "La tienda lo vende en R-36 (el gigante de las revelaciones)." },
  { id: "2-caras-feliz-cumpleanos-fantasia-reflex-surtido", nombre: "GLOBO FELIZ CUMPLEAÑOS FANTASIA", url: "/products/globo-para-fiesta-latex-redondo-2-caras-feliz-cumpleanos-fantasia-reflex-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "931", surtido: ["931", "944", "968", "971"], caras: "2 caras", ideas: 1, estampado: impreso([texto("FELIZ", TINTA.blanco, { letra: "bloque", altoGrados: 17, dyGrados: 10 }), texto("Cumpleaños", TINTA.blanco, { letra: "manuscrita", altoGrados: 13, dyGrados: -9 })], 2) },
  { id: "infinity-happy-birthday-festivo-fashion-surtido", nombre: "GLOBO REDONDO INFINITY® HAPPY BIRTHDAY FESTIVO FASHION SURTIDO", url: "/products/globo-latex-redondo-infinity-happy-birthday-festivo-fashion-surtido", formatoId: "R-12", tallas: ["R-12"], codigoBase: "012", surtido: ["012", "020", "031", "040", "061"], caras: "infinity", ideas: 1, estampado: impreso([patron("confeti", [TINTA.blanco, TINTA.amarillo], 12, 8), texto("Happy\nBirthday", TINTA.blanco, { letra: "manuscrita", altoGrados: 15 })], 2) },
];
// </datos>

/** Url relativa sin dominio ni barra final. */
const normalizar = (url: string) => url.replace(/^https?:\/\/[^/]+/, "").replace(/\/$/, "");

export function impresoPorId(id: string): ImpresoCatalogo | undefined {
  return IMPRESOS_TIENDA.find((i) => i.id === id);
}

export function impresoPorUrl(url: string): ImpresoCatalogo | undefined {
  const u = normalizar(url);
  return IMPRESOS_TIENDA.find((i) => i.url === u);
}

/** El impreso que lleva un globo de ese color (el del color si lo hay, si no el general). */
export function impresoDelColor(i: ImpresoCatalogo, codigo: string): ImpresoGlobo {
  return i.porColor?.[codigo] ?? i.estampado;
}

/**
 * Qué globos de una pieza llevan un impreso: por color (`codigo`: todos los de ese color, o uno de cada `cada`
 * empezando en `desde`) o por índice (`globos`, el orden en que la pieza los arma). Un globo ya impreso no se vuelve a
 * imprimir.
 */
export type ImpresoEnPieza =
  | { impresoId: string; codigo: string; cada?: number; desde?: number }
  | { impresoId: string; globos: number[] };

const unitario = (v: Vec3): Vec3 => { const n = Math.hypot(v.x, v.y, v.z) || 1; return { x: v.x / n, y: v.y / n, z: v.z / n }; };

/** Hacia dónde mira lo impreso: al salón (+z), perpendicular al eje del globo (y si el globo mira al salón, arriba). */
function frenteDe(direccion: Vec3): Vec3 {
  const d = unitario(direccion);
  for (const deseado of [{ x: 0, y: 0, z: 1 }, { x: 0, y: 1, z: 0 }]) {
    const k = deseado.x * d.x + deseado.y * d.y + deseado.z * d.z;
    const f = { x: deseado.x - k * d.x, y: deseado.y - k * d.y, z: deseado.z - k * d.z };
    if (Math.hypot(f.x, f.y, f.z) > 0.2) return unitario(f);
  }
  return { x: 1, y: 0, z: 0 };
}

/**
 * Pone los impresos en los globos de una pieza armada (no la cambia: devuelve copias). Ajusta los materiales (un globo
 * que pasa a un color base distinto se cuenta en ese color) y devuelve los productos de la tienda con su cantidad.
 * Los impresos que no están en el catálogo, o que no encuentran globos, salen en `avisos`.
 */
export function aplicarImpresos<G extends GloboDecoracion>(
  globos: readonly G[], materiales: readonly MaterialDecoracion[], impresos: readonly ImpresoEnPieza[],
): { globos: G[]; materiales: MaterialDecoracion[]; productos: ProductoDePieza[]; avisos: string[] } {
  const salida = globos.map((g) => ({ ...g }));
  const cuenta = new Map<string, MaterialDecoracion>(materiales.map((m) => [`${m.formatoId}|${m.codigo}`, { ...m }]));
  const productos: ProductoDePieza[] = [];
  const avisos: string[] = [];
  const yaImpresos = new Set<number>();
  for (const pedido of impresos) {
    const i = impresoPorId(pedido.impresoId);
    if (!i) { avisos.push(`Impreso desconocido: ${pedido.impresoId}`); continue; }
    let elegidos: number[];
    if ("globos" in pedido) elegidos = pedido.globos.filter((k) => k >= 0 && k < salida.length);
    else {
      const delColor = salida.map((g, k) => (g.codigo === pedido.codigo ? k : -1)).filter((k) => k >= 0);
      const cada = Math.max(1, pedido.cada ?? 1), desde = Math.max(0, pedido.desde ?? 0);
      elegidos = delColor.filter((_, n) => n >= desde && (n - desde) % cada === 0);
    }
    elegidos = elegidos.filter((k) => !yaImpresos.has(k));
    if (!elegidos.length) { avisos.push(`${i.nombre}: ningún globo lo lleva`); continue; }
    for (const k of elegidos) {
      yaImpresos.add(k);
      const g = salida[k]!;
      // Un surtido deja el color del globo (si es uno del surtido); uno de un solo color le pone el suyo.
      const codigo = i.surtido?.includes(g.codigo) ? g.codigo : i.codigoBase;
      if (codigo !== g.codigo) {
        const antes = cuenta.get(`${g.formatoId}|${g.codigo}`);
        if (antes) antes.cantidad -= 1;
        const clave = `${g.formatoId}|${codigo}`;
        const despues = cuenta.get(clave) ?? { formatoId: g.formatoId, codigo, cantidad: 0 };
        despues.cantidad += 1;
        cuenta.set(clave, despues);
      }
      salida[k] = { ...g, codigo, frente: g.frente ?? frenteDe(g.direccion), estampado: estampadoDeImpreso(impresoDelColor(i, codigo)) };
    }
    const ya = productos.find((p) => p.url === i.url);
    if (ya) ya.cantidad += elegidos.length;
    else productos.push({ nombre: i.nombre, url: i.url, cantidad: elegidos.length });
  }
  return { globos: salida, materiales: [...cuenta.values()].filter((m) => m.cantidad > 0), productos, avisos };
}
